import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { camelCase, kebabCase } from "change-case";
import { OpenAPIV3, type OpenAPIV3_1 } from "openapi-types";
import { format } from "prettier";
import { EXCLUDED_OPERATION_IDS } from "./exclusions.js";
import { formatPropertyKey, toTemplateLiteral } from "./utils.js";
import { collectObjectFields, type ObjectField, schemaToZod } from "./zod.js";

const GENERATED_HEADER =
  "// Generated by @sumup/agent-toolkit-codegen. Do not edit manually.";

type NormalizedField = ObjectField & {
  originalName: string;
  description?: string;
  location?: "path" | "query" | "body";
};

type OperationDetails = {
  operationId: string;
  paramConst: string;
  resultConst: string;
  pathParams: NormalizedField[];
  queryParams: NormalizedField[];
  bodyFields: NormalizedField[];
  bodyDescription?: string;
  responses?: OpenAPIV3_1.ResponsesObject;
};

export type CodegenOptions = {
  outputDir: string;
};

const HTTP_METHODS = [
  OpenAPIV3.HttpMethods.GET,
  OpenAPIV3.HttpMethods.POST,
  OpenAPIV3.HttpMethods.PUT,
  OpenAPIV3.HttpMethods.PATCH,
  OpenAPIV3.HttpMethods.DELETE,
];

export async function generate(
  spec: OpenAPIV3_1.Document,
  options: CodegenOptions,
) {
  const excludedOperationIds = new Set<string>(EXCLUDED_OPERATION_IDS);
  const operationsByTag = collectOperations(spec, excludedOperationIds);
  if (!operationsByTag) {
    return;
  }

  const entries = Array.from(operationsByTag.entries()).sort(([a], [b]) =>
    a.localeCompare(b),
  );
  mkdirSync(options.outputDir, { recursive: true });
  const generatedFiles = new Set(
    entries.map(([tag]) => `${kebabCase(tag)}.ts`),
  );
  // Delete only files owned by this generator, never handwritten tool modules.
  for (const entry of readdirSync(options.outputDir, { withFileTypes: true })) {
    if (
      !entry.isFile() ||
      !entry.name.endsWith(".ts") ||
      generatedFiles.has(entry.name)
    )
      continue;
    const file = join(options.outputDir, entry.name);
    if (readFileSync(file, "utf8").startsWith(GENERATED_HEADER)) rmSync(file);
  }
  for (const [tag, operations] of entries) {
    await writeParametersFile(
      resolve(options.outputDir, `${kebabCase(tag)}.ts`),
      operations,
    );
  }
}

function collectOperations(
  spec: OpenAPIV3_1.Document,
  excludedOperationIds: Set<string>,
) {
  const map = new Map<string, OperationDetails[]>();

  for (const pathItem of Object.values(spec.paths ?? {})) {
    if (!pathItem) continue;

    const sharedParams = pathItem.parameters ?? [];

    for (const method of HTTP_METHODS) {
      const operation = pathItem[method];
      if (!operation) {
        continue;
      }

      if ("$ref" in operation) {
        continue;
      }

      if (
        !operation.operationId ||
        !operation.tags ||
        operation.tags.length === 0
      ) {
        continue;
      }

      if (operation.deprecated) {
        continue;
      }

      const tag = operation.tags[0]!;
      const operationId = operation.operationId;
      if (excludedOperationIds.has(operationId)) {
        continue;
      }
      const name = camelCase(operationId);
      const paramConst = `${name}Parameters`;
      const resultConst = `${name}Result`;

      const allParams = [
        ...sharedParams,
        ...(operation.parameters ?? []),
      ] as OpenAPIV3_1.ParameterObject[];
      const normalized = normalizeParameters(allParams);

      const pathParams = normalized.filter(
        (param) => param.location === "path",
      );
      const queryParams = normalized.filter(
        (param) => param.location === "query",
      );

      const { bodyFields, bodyDescription } = normalizeRequestBody(
        operation.requestBody as OpenAPIV3_1.RequestBodyObject | undefined,
      );

      const details: OperationDetails = {
        operationId,
        paramConst,
        resultConst,
        pathParams,
        queryParams,
        bodyFields,
        bodyDescription,
        responses: operation.responses,
      };

      const existing = map.get(tag);
      if (existing) {
        existing.push(details);
      } else {
        map.set(tag, [details]);
      }
    }
  }

  for (const [, list] of map) {
    list.sort((a, b) => a.operationId.localeCompare(b.operationId));
  }

  return map;
}

function normalizeParameters(params: OpenAPIV3_1.ParameterObject[]) {
  const seen = new Map<
    string,
    NormalizedField & { location: "path" | "query" }
  >();

  for (const param of params) {
    if (!param || (param.in !== "path" && param.in !== "query")) {
      continue;
    }
    const schema = resolveParameterSchema(param);
    if (!schema) continue;

    const name =
      param.in === "path"
        ? camelCase(param.name)
        : schema.type === "array" && param.name.endsWith("[]")
          ? param.name.slice(0, -2)
          : param.name;
    const key = `${param.in}:${name}`;

    if (seen.has(key)) {
      continue;
    }

    seen.set(key, {
      name,
      originalName: param.name,
      schema: schema as OpenAPIV3_1.SchemaObject,
      required: param.required ?? param.in === "path",
      description: param.description,
      location: param.in,
    });
  }

  return Array.from(seen.values());
}

function resolveParameterSchema(param: OpenAPIV3_1.ParameterObject) {
  if (param.schema) {
    return param.schema as OpenAPIV3_1.SchemaObject;
  }

  const content = param.content ?? {};
  const first = content["application/json"] ?? Object.values(content)[0];
  return first?.schema as OpenAPIV3_1.SchemaObject | undefined;
}

function normalizeRequestBody(requestBody?: OpenAPIV3_1.RequestBodyObject) {
  if (!requestBody || !requestBody.content) {
    return { bodyFields: [], bodyDescription: undefined };
  }

  const jsonContent =
    requestBody.content["application/json"] ??
    requestBody.content["application/x-www-form-urlencoded"] ??
    Object.values(requestBody.content)[0];

  const schema = jsonContent?.schema as OpenAPIV3_1.SchemaObject | undefined;
  if (!schema) {
    return { bodyFields: [], bodyDescription: undefined };
  }

  const fields = collectObjectFields(schema).map((field) => ({
    ...field,
    originalName: field.name,
  }));

  return {
    bodyFields: fields,
    bodyDescription: schema.description?.trim(),
  };
}

async function writeParametersFile(
  file: string,
  operations: OperationDetails[],
) {
  const parts: string[] = [GENERATED_HEADER, `import { z } from "zod";`, ""];

  for (const operation of operations) {
    parts.push(
      `export const ${operation.paramConst} = ${buildParameterSchema(operation)};`,
      "",
    );
    parts.push(
      `export const ${operation.resultConst} = ${buildResultSchema(operation)};`,
      "",
    );
  }

  const content = await format(parts.join("\n").trimEnd(), {
    parser: "typescript",
  });
  writeFileSync(file, `${content}\n`);
}

function buildParameterSchema(operation: OperationDetails) {
  const fields = [
    ...operation.pathParams,
    ...operation.queryParams,
    ...operation.bodyFields,
  ];
  const shape: string[] = [];

  for (const field of fields) {
    const schemaResult = schemaToZod(field.schema);
    let expr = schemaResult.code;
    if (!field.required) {
      expr += ".optional()";
    }

    if (!schemaResult.hasDescription && field.description) {
      expr += `.describe(${toTemplateLiteral(field.description)})`;
    }

    shape.push(`${formatPropertyKey(field.name)}: ${expr}`);
  }

  let expression = `z.object({${shape.length > 0 ? `\n  ${shape.join(",\n  ")}\n` : ""}})`;

  if (operation.bodyDescription) {
    expression += `.describe(${toTemplateLiteral(operation.bodyDescription)})`;
  }

  return expression;
}

function buildResultSchema(operation: OperationDetails) {
  const responses = operation.responses ?? operation.responses;
  if (!responses || typeof responses !== "object") {
    return "z.any()";
  }

  // Collect all 2xx responses
  const successEntries = Object.entries(responses)
    .filter(([code]) => /^2\d\d$/.test(code))
    .sort(([a], [b]) => a.localeCompare(b));

  // If no explicit 2xx, fall back to the first response if present
  const [, responseObj] =
    successEntries[0] ?? Object.entries(responses)[0] ?? [];

  if (!responseObj || typeof responseObj !== "object") {
    return "z.any()";
  }

  const resp = responseObj as OpenAPIV3_1.ResponseObject;
  const content = resp.content;
  if (!content || typeof content !== "object") {
    return "z.any()";
  }

  // Prioritize JSON types, fall back to first available
  const json =
    content["application/json"] ??
    content["application/*+json"] ??
    Object.values(content)[0];

  if (!json || !json.schema) {
    return "z.any()";
  }

  const schema = json.schema as OpenAPIV3_1.SchemaObject;
  const schemaResult = schemaToZod(schema, {
    allowNullableAdditionalProperties: true,
    looseEmptyObject: true,
    passthroughObjects: true,
  });

  let expr = schemaResult.code;

  // Add description if the schema did not already include one
  if (!schemaResult.hasDescription && typeof resp.description === "string") {
    expr += `.describe(${toTemplateLiteral(resp.description.trim())})`;
  }

  return expr;
}
