// Generated by @sumup/agent-toolkit-codegen. Do not edit manually.

import {
  createCheckout,
  deactivateCheckout,
  getCheckout,
  listCheckouts,
  updateCheckout,
} from "./checkouts";
import {
  createCustomer,
  getCustomer,
  listPaymentInstruments,
  updateCustomer,
} from "./customers";
import {
  createMerchantMember,
  deleteMerchantMember,
  getMerchantMember,
  listMerchantMembers,
  updateMerchantMember,
} from "./members";
import { listMemberships } from "./memberships";
import { getMerchant, getPerson, listPersons } from "./merchants";
import { listPayoutsV1 } from "./payouts";
import {
  createGoReaderCheckout,
  createReader,
  createReaderCheckout,
  createReaderTerminate,
  deleteReader,
  getReader,
  getReaderCheckout,
  getReaderStatus,
  listReaders,
  updateReader,
} from "./readers";
import { getReceipt } from "./receipts";
import {
  createMerchantRole,
  deleteMerchantRole,
  getMerchantRole,
  listMerchantRoles,
  updateMerchantRole,
} from "./roles";
import {
  getTransactionV2_1,
  listTransactionsV2_1,
  refundTransaction,
} from "./transactions";
import type { Tool } from "./types";

/** Names of tools available for registration, excluding unsupported operations. */
export type ToolName =
  | "create_checkout"
  | "create_customer"
  | "create_go_reader_checkout"
  | "create_merchant_member"
  | "create_merchant_role"
  | "create_reader"
  | "create_reader_checkout"
  | "create_reader_terminate"
  | "deactivate_checkout"
  | "delete_merchant_member"
  | "delete_merchant_role"
  | "delete_reader"
  | "get_checkout"
  | "get_customer"
  | "get_merchant"
  | "get_merchant_member"
  | "get_merchant_role"
  | "get_person"
  | "get_reader"
  | "get_reader_checkout"
  | "get_reader_status"
  | "get_receipt"
  | "get_transaction_v2_1"
  | "list_checkouts"
  | "list_memberships"
  | "list_merchant_members"
  | "list_merchant_roles"
  | "list_payment_instruments"
  | "list_payouts_v1"
  | "list_persons"
  | "list_readers"
  | "list_transactions_v2_1"
  | "refund_transaction"
  | "update_checkout"
  | "update_customer"
  | "update_merchant_member"
  | "update_merchant_role"
  | "update_reader";

export const registerTools = (reg: (tool: Tool) => void) => {
  reg(createCheckout);
  reg(createCustomer);
  reg(createGoReaderCheckout);
  reg(createMerchantMember);
  reg(createMerchantRole);
  reg(createReader);
  reg(createReaderCheckout);
  reg(createReaderTerminate);
  reg(deactivateCheckout);
  reg(deleteMerchantMember);
  reg(deleteMerchantRole);
  reg(deleteReader);
  reg(getCheckout);
  reg(getCustomer);
  reg(getMerchant);
  reg(getMerchantMember);
  reg(getMerchantRole);
  reg(getPerson);
  reg(getReader);
  reg(getReaderCheckout);
  reg(getReaderStatus);
  reg(getReceipt);
  reg(getTransactionV2_1);
  reg(listCheckouts);
  reg(listMemberships);
  reg(listMerchantMembers);
  reg(listMerchantRoles);
  reg(listPaymentInstruments);
  reg(listPayoutsV1);
  reg(listPersons);
  reg(listReaders);
  reg(listTransactionsV2_1);
  reg(refundTransaction);
  reg(updateCheckout);
  reg(updateCustomer);
  reg(updateMerchantMember);
  reg(updateMerchantRole);
  reg(updateReader);
};
