import { z } from "zod";

export const createReaderParameters = z.object({
  merchantCode: z
    .string()
    .describe(`Short unique identifier for the merchant.`),
  pairing_code: z
    .string()
    .min(8)
    .max(9)
    .describe(
      `The pairing code is a 8 or 9 character alphanumeric string that is displayed on a SumUp Device after initiating the pairing. It is used to link the physical device to the created pairing.`,
    ),
  name: z
    .string()
    .max(500)
    .describe(
      `Custom human-readable, user-defined name for easier identification of the reader.`,
    ),
  metadata: z
    .object({})
    .catchall(z.unknown())
    .describe(
      `Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.`,
    )
    .optional(),
});

export const createReaderResult = z
  .object({
    id: z
      .string()
      .min(30)
      .max(30)
      .describe(`Unique identifier of the object.

Note that this identifies the instance of the physical devices pairing with your SumUp account. If you [delete](https://developer.sumup.com/api/readers/delete-reader) a reader, and pair the device again, the ID will be different. Do not use this ID to refer to a physical device.`),
    name: z
      .string()
      .max(500)
      .describe(
        `Custom human-readable, user-defined name for easier identification of the reader.`,
      ),
    status: z
      .enum(["unknown", "processing", "paired", "expired"])
      .describe(`The status of the reader object gives information about the current state of the reader.

Possible values:

- \`unknown\` - The reader status is unknown.
- \`processing\` - The reader is created and waits for the physical device to confirm the pairing.
- \`paired\` - The reader is paired with a merchant account and can be used with SumUp APIs.
- \`expired\` - The pairing is expired and no longer usable with the account. The resource needs to get recreated.`),
    device: z
      .object({
        identifier: z
          .string()
          .describe(
            `A unique identifier of the physical device (e.g. serial number).`,
          ),
        model: z
          .enum(["solo", "virtual-solo"])
          .describe(`Identifier of the model of the device.`),
      })
      .describe(`Information about the underlying physical device.`),
    metadata: z
      .object({})
      .catchall(z.unknown())
      .nullable()
      .describe(
        `Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.`,
      )
      .optional(),
    service_account_id: z
      .string()
      .describe(
        `Identifier of the system-managed service account associated with this reader.
Present only for readers that are already paired.
This field is currently in beta and may change.`,
      )
      .optional(),
    created_at: z
      .string()
      .describe(`The timestamp of when the reader was created.`),
    updated_at: z
      .string()
      .describe(`The timestamp of when the reader was last updated.`),
  })
  .passthrough()
  .describe(
    `A physical card reader device that can accept in-person payments.`,
  );

export const createReaderCheckoutParameters = z
  .object({
    merchantCode: z.string().describe(`Merchant Code`),
    readerId: z.string().describe(`The unique identifier of the Reader`),
    affiliate: z
      .object({
        app_id: z.string().describe(`Application ID of the affiliate.
It is a unique identifier for the application and should be set by the integrator in the [Affiliate Keys](https://developer.sumup.com/affiliate-keys) page.
`),
        foreign_transaction_id: z
          .string()
          .describe(`Foreign transaction ID of the affiliate.
It is a unique identifier for the transaction.
It can be used later to fetch the transaction details via the [Transactions API](https://developer.sumup.com/api/transactions/get).
`),
        key: z.string().describe(`Key of the affiliate.
It is a unique identifier for the key  and should be generated by the integrator in the [Affiliate Keys](https://developer.sumup.com/affiliate-keys) page.
`),
        tags: z
          .object({})
          .catchall(z.unknown())
          .describe(
            `Additional metadata for the transaction.
It is key-value object that can be associated with the transaction.
`,
          )
          .optional(),
      })
      .nullable()
      .describe(
        `Affiliate metadata for the transaction.
It is a field that allow for integrators to track the source of the transaction.
`,
      )
      .optional(),
    card_type: z
      .enum(["credit", "debit"])
      .describe(
        `The card type of the card used for the transaction.
Is is required only for some countries (e.g: Brazil).
`,
      )
      .optional(),
    description: z
      .string()
      .describe(`Description of the checkout to be shown in the Merchant Sales`)
      .optional(),
    installments: z
      .number()
      .int()
      .nullable()
      .describe(
        `Number of installments for the transaction.
It may vary according to the merchant country.
For example, in Brazil, the maximum number of installments is 12.

Omit if the merchant country does support installments.
Otherwise, the checkout will be rejected.
`,
      )
      .optional(),
    return_url: z
      .string()
      .describe(
        `Webhook URL to which the payment result will be sent.
It must be a HTTPS url.
`,
      )
      .optional(),
    tip_rates: z
      .array(z.number())
      .describe(
        `List of tipping rates to be displayed to the cardholder.
The rates are in percentage and should be between 0.01 and 0.99.
The list should be sorted in ascending order.
`,
      )
      .optional(),
    tip_timeout: z
      .number()
      .int()
      .describe(
        `Time in seconds the cardholder has to select a tip rate.
If not provided, the default value is 30 seconds.

It can only be set if \`tip_rates\` is provided.

**Note**: If the target device is a Solo, it must be in version 3.3.38.0 or higher.
`,
      )
      .optional(),
    total_amount: z
      .object({
        currency: z.string().describe(`Currency ISO 4217 code`),
        minor_unit: z
          .number()
          .int()
          .describe(`The minor units of the currency.
It represents the number of decimals of the currency. For the currencies CLP, COP and HUF, the minor unit is 0.
`),
        value: z.number().int().describe(`Integer value of the amount.`),
      })
      .describe(`Amount structure.

The amount is represented as an integer value altogether with the currency and the minor unit.

For example, EUR 1.00 is represented as value 100 with minor unit of 2.
`),
  })
  .describe(`Reader Checkout`);

export const createReaderCheckoutResult = z
  .object({
    data: z.object({
      client_transaction_id: z
        .string()
        .describe(`The client transaction ID is a unique identifier for the transaction that is generated for the client.

It can be used later to fetch the transaction details via the [Transactions API](https://developer.sumup.com/api/transactions/get).
`),
    }),
  })
  .passthrough()
  .describe(`The Checkout got successfully created for the given reader.`);

export const createReaderTerminateParameters = z.object({
  merchantCode: z.string().describe(`Merchant Code`),
  readerId: z.string().describe(`The unique identifier of the Reader`),
});

export const createReaderTerminateResult = z.any();

export const deleteReaderParameters = z.object({
  merchantCode: z
    .string()
    .describe(`Short unique identifier for the merchant.`),
  id: z
    .string()
    .min(30)
    .max(30)
    .describe(`Unique identifier of the object.

Note that this identifies the instance of the physical devices pairing with your SumUp account. If you [delete](https://developer.sumup.com/api/readers/delete-reader) a reader, and pair the device again, the ID will be different. Do not use this ID to refer to a physical device.`),
});

export const deleteReaderResult = z.any();

export const getReaderParameters = z.object({
  merchantCode: z
    .string()
    .describe(`Short unique identifier for the merchant.`),
  id: z
    .string()
    .min(30)
    .max(30)
    .describe(`Unique identifier of the object.

Note that this identifies the instance of the physical devices pairing with your SumUp account. If you [delete](https://developer.sumup.com/api/readers/delete-reader) a reader, and pair the device again, the ID will be different. Do not use this ID to refer to a physical device.`),
});

export const getReaderResult = z
  .object({
    id: z
      .string()
      .min(30)
      .max(30)
      .describe(`Unique identifier of the object.

Note that this identifies the instance of the physical devices pairing with your SumUp account. If you [delete](https://developer.sumup.com/api/readers/delete-reader) a reader, and pair the device again, the ID will be different. Do not use this ID to refer to a physical device.`),
    name: z
      .string()
      .max(500)
      .describe(
        `Custom human-readable, user-defined name for easier identification of the reader.`,
      ),
    status: z
      .enum(["unknown", "processing", "paired", "expired"])
      .describe(`The status of the reader object gives information about the current state of the reader.

Possible values:

- \`unknown\` - The reader status is unknown.
- \`processing\` - The reader is created and waits for the physical device to confirm the pairing.
- \`paired\` - The reader is paired with a merchant account and can be used with SumUp APIs.
- \`expired\` - The pairing is expired and no longer usable with the account. The resource needs to get recreated.`),
    device: z
      .object({
        identifier: z
          .string()
          .describe(
            `A unique identifier of the physical device (e.g. serial number).`,
          ),
        model: z
          .enum(["solo", "virtual-solo"])
          .describe(`Identifier of the model of the device.`),
      })
      .describe(`Information about the underlying physical device.`),
    metadata: z
      .object({})
      .catchall(z.unknown())
      .nullable()
      .describe(
        `Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.`,
      )
      .optional(),
    service_account_id: z
      .string()
      .describe(
        `Identifier of the system-managed service account associated with this reader.
Present only for readers that are already paired.
This field is currently in beta and may change.`,
      )
      .optional(),
    created_at: z
      .string()
      .describe(`The timestamp of when the reader was created.`),
    updated_at: z
      .string()
      .describe(`The timestamp of when the reader was last updated.`),
  })
  .passthrough()
  .describe(
    `A physical card reader device that can accept in-person payments.`,
  );

export const getReaderStatusParameters = z.object({
  merchantCode: z.string().describe(`Merchant Code`),
  readerId: z.string().describe(`The unique identifier of the Reader`),
});

export const getReaderStatusResult = z
  .object({
    data: z.object({
      battery_level: z.number().describe(`Battery level percentage`).optional(),
      battery_temperature: z
        .number()
        .int()
        .describe(`Battery temperature in Celsius`)
        .optional(),
      connection_type: z
        .enum(["btle", "edge", "gprs", "lte", "umts", "usb", "Wi-Fi"])
        .describe(`Type of connection used by the device`)
        .optional(),
      firmware_version: z
        .string()
        .describe(`Firmware version of the device`)
        .optional(),
      last_activity: z
        .string()
        .describe(`Timestamp of the last activity from the device`)
        .optional(),
      state: z
        .enum([
          "IDLE",
          "SELECTING_TIP",
          "WAITING_FOR_CARD",
          "WAITING_FOR_PIN",
          "WAITING_FOR_SIGNATURE",
          "UPDATING_FIRMWARE",
        ])
        .describe(`Latest state of the device`)
        .optional(),
      status: z.enum(["ONLINE", "OFFLINE"]).describe(`Status of a device`),
    }),
  })
  .passthrough()
  .describe(`Status of a device`);

export const listReadersParameters = z.object({
  merchantCode: z
    .string()
    .describe(`Short unique identifier for the merchant.`),
});

export const listReadersResult = z
  .object({
    items: z.array(
      z
        .object({
          id: z
            .string()
            .min(30)
            .max(30)
            .describe(`Unique identifier of the object.

Note that this identifies the instance of the physical devices pairing with your SumUp account. If you [delete](https://developer.sumup.com/api/readers/delete-reader) a reader, and pair the device again, the ID will be different. Do not use this ID to refer to a physical device.`),
          name: z
            .string()
            .max(500)
            .describe(
              `Custom human-readable, user-defined name for easier identification of the reader.`,
            ),
          status: z
            .enum(["unknown", "processing", "paired", "expired"])
            .describe(`The status of the reader object gives information about the current state of the reader.

Possible values:

- \`unknown\` - The reader status is unknown.
- \`processing\` - The reader is created and waits for the physical device to confirm the pairing.
- \`paired\` - The reader is paired with a merchant account and can be used with SumUp APIs.
- \`expired\` - The pairing is expired and no longer usable with the account. The resource needs to get recreated.`),
          device: z
            .object({
              identifier: z
                .string()
                .describe(
                  `A unique identifier of the physical device (e.g. serial number).`,
                ),
              model: z
                .enum(["solo", "virtual-solo"])
                .describe(`Identifier of the model of the device.`),
            })
            .describe(`Information about the underlying physical device.`),
          metadata: z
            .object({})
            .catchall(z.unknown())
            .nullable()
            .describe(
              `Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.`,
            )
            .optional(),
          service_account_id: z
            .string()
            .describe(
              `Identifier of the system-managed service account associated with this reader.
Present only for readers that are already paired.
This field is currently in beta and may change.`,
            )
            .optional(),
          created_at: z
            .string()
            .describe(`The timestamp of when the reader was created.`),
          updated_at: z
            .string()
            .describe(`The timestamp of when the reader was last updated.`),
        })
        .describe(
          `A physical card reader device that can accept in-person payments.`,
        ),
    ),
  })
  .passthrough()
  .describe(`Returns a list Reader objects.`);

export const updateReaderParameters = z.object({
  merchantCode: z
    .string()
    .describe(`Short unique identifier for the merchant.`),
  id: z
    .string()
    .min(30)
    .max(30)
    .describe(`Unique identifier of the object.

Note that this identifies the instance of the physical devices pairing with your SumUp account. If you [delete](https://developer.sumup.com/api/readers/delete-reader) a reader, and pair the device again, the ID will be different. Do not use this ID to refer to a physical device.`),
  name: z
    .string()
    .max(500)
    .describe(
      `Custom human-readable, user-defined name for easier identification of the reader.`,
    )
    .optional(),
  metadata: z
    .object({})
    .catchall(z.unknown())
    .describe(
      `Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.`,
    )
    .optional(),
});

export const updateReaderResult = z
  .object({
    id: z
      .string()
      .min(30)
      .max(30)
      .describe(`Unique identifier of the object.

Note that this identifies the instance of the physical devices pairing with your SumUp account. If you [delete](https://developer.sumup.com/api/readers/delete-reader) a reader, and pair the device again, the ID will be different. Do not use this ID to refer to a physical device.`),
    name: z
      .string()
      .max(500)
      .describe(
        `Custom human-readable, user-defined name for easier identification of the reader.`,
      ),
    status: z
      .enum(["unknown", "processing", "paired", "expired"])
      .describe(`The status of the reader object gives information about the current state of the reader.

Possible values:

- \`unknown\` - The reader status is unknown.
- \`processing\` - The reader is created and waits for the physical device to confirm the pairing.
- \`paired\` - The reader is paired with a merchant account and can be used with SumUp APIs.
- \`expired\` - The pairing is expired and no longer usable with the account. The resource needs to get recreated.`),
    device: z
      .object({
        identifier: z
          .string()
          .describe(
            `A unique identifier of the physical device (e.g. serial number).`,
          ),
        model: z
          .enum(["solo", "virtual-solo"])
          .describe(`Identifier of the model of the device.`),
      })
      .describe(`Information about the underlying physical device.`),
    metadata: z
      .object({})
      .catchall(z.unknown())
      .nullable()
      .describe(
        `Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.`,
      )
      .optional(),
    service_account_id: z
      .string()
      .describe(
        `Identifier of the system-managed service account associated with this reader.
Present only for readers that are already paired.
This field is currently in beta and may change.`,
      )
      .optional(),
    created_at: z
      .string()
      .describe(`The timestamp of when the reader was created.`),
    updated_at: z
      .string()
      .describe(`The timestamp of when the reader was last updated.`),
  })
  .passthrough()
  .describe(
    `A physical card reader device that can accept in-person payments.`,
  );
